apiVersion: apps/v1
kind: Deployment
  name: todo
  namespace: todorest
spec:
  replicas: 2
  selector:
    matchlabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todorest-app
        - image: anilbidari/todo:latest
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP


