apiVersion: v1
kind: ReplicationController
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    app: webapp
  template:
    metadata:
      labels:
        app: webapp
      name: webapp
    spec:
      containers:
        - image: 'anilbidari/todo:8.0'
          imagePullPolicy: IfNotPresent
          name: webapp
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
    service: webapp
  name: webapp
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
