---
- hosts: localhost
  become_user: jenkins
  tasks:

  - name: Download jar file
    get_url:
      url: http://192.168.181.242:8081/repository/maven-releases/todorest-0.0.1-SNAPSHOT.jar
      user: 'admin'
      password: "root123"
      body_format: json
      method: POST
      force_basic_auth: yes
      status_code: 204
      dest: /home/jenkins

  - name: run jar file
    shell: nohup java -jar todorest-0.0.1-SNAPSHOT.jar /tmp 2>> /dev/null >> /dev/null &
