---
- hosts: localhost
  become_user: jenkins
  tasks:

  - name: Download jar file
    get_url:
      url: http://192.168.181.242:8081/repository/maven-releases/todorest-0.0.1-SNAPSHOT.jar
      url_username: 'admin'
      url_password: "root123"
      force_basic_auth: yes
      dest: /home/jenkins

  - name: run jar file
    shell: cd /home/jenkins
    shell: nohup java -jar todorest-0.0.1-SNAPSHOT.jar /tmp 2>> /dev/null >> /dev/null &
