apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weather-forecast
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
      labels:
        app: weather-forecast
        service: webapp
    spec:
      containers:
        - image: 'anilbidari/todo:3.0'
          imagePullPolicy: IfNotPresent
          name: webapp
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: weather-forecast
    service: webapp
  name: webapp
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    service: webapp
  type: LoadBalancer  #1010
